### ISSUE TITLE
UI enhancements, Fixing Bugs and Responsiveness

### ISSUE THREAD

**Issue by vastavikadi** [Yash-Ainapure/dypcetclubs.live#71]
## Issue Description

The landing page needs improvements to its responsiveness and UI. Additionally, there are bugs to be fixed, and the skeleton of the pages should be built. The following tasks are needed:

### Tasks
1. **Fix Responsiveness**
2. **Enhance UI**
   - Add a responsive navbar with links to all sections.
   - Improve the hero section with a better CTA and relevant background.
   - Highlight key features with appropriate icons and styles.
   - Create a footer with links like Privacy Policy, Terms of Service, and social media.

3. **Fix Existing Bugs**
4. **Build the Skeleton of Pages**
   - Create basic layouts for Clubs, Hiring & Events pages.
   - Add placeholders for content to help with future development.

### Expected Outcome
The landing page will be fully responsive with an enhanced UI, fixed bugs, and a well-structured skeleton of pages ready for future development.

### Checklist

- [x] I have checked the existing issues.
- [x] I have read the Contributing Guidelines.
- [x] I am a GSSoC'24-Extd contributor.
- [x] I am a Hacktoberfest'24 contributor.
- [x] I am willing to work on this issue.

**Comment by vastavikadi** [comment]
@Yash-Ainapure please assign it to me

**Comment by Yash-Ainapure** [comment]
> ## Issue Description
> The landing page needs improvements to its responsiveness and UI. Additionally, there are bugs to be fixed, and the skeleton of the pages should be built. The following tasks are needed:
> 
> ### Tasks
> 1. **Fix Responsiveness**
> 2. **Enhance UI**
>    
>    * Add a responsive navbar with links to all sections.
>    * Improve the hero section with a better CTA and relevant background.
>    * Highlight key features with appropriate icons and styles.
>    * Create a footer with links like Privacy Policy, Terms of Service, and social media.
> 3. **Fix Existing Bugs**
> 4. **Build the Skeleton of Pages**
>    
>    * Create basic layouts for Clubs, Hiring & Events pages.
>    * Add placeholders for content to help with future development.
> 
> ### Expected Outcome
> The landing page will be fully responsive with an enhanced UI, fixed bugs, and a well-structured skeleton of pages ready for future development.
> 
> ### Checklist
> * [x]  I have checked the existing issues.
> * [x]  I have read the Contributing Guidelines.
> * [x]  I am a GSSoC'24-Extd contributor.
> * [x]  I am a Hacktoberfest'24 contributor.
> * [x]  I am willing to work on this issue.

Great,do you want to work on it?
The level of the issue will depend on the work you do

**Comment by vastavikadi** [comment]
@Yash-Ainapure I have sent the pull request for this.
